### ISSUE TITLE
Multiple sliders on a page influence each other

### ISSUE THREAD

**Issue by bsvkb** [tb/ng2-nouislider#88]
I add multiple sliders to a page:

`<div class="row form-row" *ngFor="let option of categoricalOptions">`
  `...`
`<categorical-slider [value]="option.defaultStringValue" [values]="option.stringValues" (sliderPosition)="onCategoricalOptionChange(option, $event)"></categorical-slider>`
`</div>`
`<div class="row form-row" *ngFor="let option of continuousOptions">`
          `...`
            `<continuous-slider [value]="option.defaultDoubleValue" [min]="option.minDoubleValue" [max]="option.maxDoubleValue" (sliderValue)="onContinuousOptionChange(option, $event)"></continuous-slider>`
`</div>`

with categorical-slider
`<div class="slider"><nouislider [config]="sliderConfig" [(ngModel)]="sliderValue" (ngModelChange)="onChange($event)"></nouislider></div>`

and continous-slider
`<div class="slider"><nouislider [config]="sliderConfig" [(ngModel)]="value" (ngModelChange)="onChange($event)"></nouislider></div>`

The sliders influence each other after being dragged once on dragging and tapping. Key events do not influence other sliders. This behaviour is not intended!

Here a screen record of the mentioned behaviour:
[screen_record-1.zip](https://github.com/tb/ng2-nouislider/files/1091563/screen_record-1.zip)

**Comment by koganei** [comment]
I'm having the same issue.
It doesn't seem to come from having multiple sliders for me, but rather as soon as I click on a handle, it becomes draggable from anywhere on the page. It looks like the same behaviour as the attached video from @bsvkb. The mousemove event handler seems to be on the html element rather than being restricted to the slider itself.

**Comment by Gagaro** [comment]
I solved the "draggable from anywhere" by installing nouislider ^9.0.0 (I had 10.0.0).

**Comment by bsvkb** [comment]
Thanks @Gagaro. Your fix is working for me too.

**Comment by cmaart** [comment]
Clicking on a handle with version 10.0.0 has the issue that it's not release properly. And you can drag anywhere on the page.

I made a plunker to reproduce it: https://plnkr.co/edit/HyFbhD?p=preview

As @Gagaro wrote, by changing the nouislider version from 10.0.0 to 9.0.0 in the systemjs config file, fixes the issue.

**Comment by saverag** [comment]
@Gagaro thanks!

**Comment by alekaizer** [comment]
@Gagaro isn't ^9.0.0 will install higher than 9.0.0 
and ^10.0.0 higher than 10.0.0

meanwhile if there's 10.1.0 both ^9.0.0 and 10.0.0 will both end up installing 10.1.0

I'm saying that because, I've got the 10.1.0 and I still have the dragging issue

even after the handle lose focus, when I hold the mouse down, and drag around, the slider changes value.

and everytime I enter the view, the end event is fired

**Comment by Gagaro** [comment]
>=9.0.0 will install any version higher than 9.0.0 (including 10.x.x).
^9.0.0 will install the last version starting with 9.

See https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004 for more information.
